import Head from 'next/head';
import '../styles/globals.css';
import '../styles/tweet.css';
import '../styles/login.css';
import '../styles/home.css';
import '../styles/sidebar.css';
import '../styles/user.css';
import '../styles/editProfile.css';
import '../styles/floatingIcon.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'antd/dist/antd.css';
import { useEffect, useState } from 'react';

function MyApp({ Component, pageProps }) {
  const [isLogin, setIsLogin] = useState(true)
  useEffect(() => {
    if (!localStorage.getItem('access_token')) {
      setIsLogin(false)
    }
  }, [])
  return (
    <>
      <Head>
          <title>Twitter--</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='' />
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossOrigin="anonymous" referrerpolicy="no-referrer" />
      </Head>
      <Component {...pageProps} isLogin={isLogin} setIsLogin={setIsLogin}/>
    </>
  )
}

export default MyApp
